version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - "./.env.production"
    environment:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro